=== evanzeller/cmd-payroll/payroll.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="employee">
    <xs:complexType>
        <xs:sequence>
            <xs:group ref="objectGroup" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:group name="objectGroup">
    <xs:choice>
        <xs:element name="hourlyEmployee" type="hourlyType"/>
        <xs:element name="salaryEmployee" type="salaryType"/>
    </xs:choice>
</xs:group>

<xs:group name="objectmembersGroup">
    <xs:sequence>
        <xs:element name="firstName" type="xs:string"/>
        <xs:element name="lastName" type="xs:string"/>
    </xs:sequence>
</xs:group>

<xs:complexType name="hourlyType">
    <xs:sequence>
        <xs:group ref="objectmembersGroup"/>
        <xs:element name="hours" type="xs:double"/>
        <xs:element name="payRate" type="xs:double"/>
        <xs:element name="overtime" type="xs:double"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="salaryType">
    <xs:sequence>
        <xs:group ref="objectmembersGroup"/>
        <xs:element name="payRate" type="xs:double"/>
    </xs:sequence>
</xs:complexType>

</xs:schema>

=== evanzeller/cmd-payroll/employees.xml
<?xml version="1.0" encoding="utf-8"?>
<employee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="payroll.xsd">
    <hourlyEmployee>
        <firstName>John</firstName>
        <lastName>Smith</lastName>
        <hours>40</hours>
        <payRate>10.50</payRate>
        <overtime>5.00</overtime>
    </hourlyEmployee>

    <salaryEmployee>
        <firstName>David</firstName>
        <lastName>Jones</lastName>
        <payRate>30000</payRate>
    </salaryEmployee>

</employee>
